CREATE DATABASE IF NOT EXISTS jktech CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE jktech;
CREATE TABLE users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) UNIQUE NOT NULL,phone VARCHAR(30),password_hash VARCHAR(255) NOT NULL,role ENUM('customer','admin') DEFAULT 'customer',status ENUM('active','blocked') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categories(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,slug VARCHAR(120) UNIQUE NOT NULL);
CREATE TABLE vehicles(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,make VARCHAR(80) NOT NULL,model VARCHAR(100) NOT NULL,year_from SMALLINT,year_to SMALLINT,engine VARCHAR(80));
CREATE TABLE products(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id INT UNSIGNED NULL,brand VARCHAR(100) NOT NULL,name VARCHAR(180) NOT NULL,slug VARCHAR(200) UNIQUE,oem_number VARCHAR(100),description TEXT,price DECIMAL(12,2) NOT NULL DEFAULT 0,stock INT NOT NULL DEFAULT 0,condition_grade ENUM('A','B','C') DEFAULT 'B',status ENUM('active','inactive','sold_out') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE product_images(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id INT UNSIGNED NOT NULL,image_path VARCHAR(255) NOT NULL,is_primary TINYINT(1) DEFAULT 0,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE product_vehicle_fitment(product_id INT UNSIGNED NOT NULL,vehicle_id INT UNSIGNED NOT NULL,PRIMARY KEY(product_id,vehicle_id),FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE);
CREATE TABLE addresses(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,address_line VARCHAR(255) NOT NULL,city VARCHAR(100) NOT NULL,postal_code VARCHAR(20),phone VARCHAR(30),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE orders(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,total_amount DECIMAL(12,2) NOT NULL,status ENUM('pending','confirmed','processing','shipped','delivered','cancelled') DEFAULT 'pending',shipping_address VARCHAR(255),shipping_city VARCHAR(100),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE order_items(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,quantity INT UNSIGNED NOT NULL,unit_price DECIMAL(12,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE payments(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,method ENUM('cash_on_delivery','bank_transfer','card') DEFAULT 'cash_on_delivery',amount DECIMAL(12,2) NOT NULL,status ENUM('pending','paid','failed','refunded') DEFAULT 'pending',transaction_ref VARCHAR(150),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
INSERT INTO categories(name,slug) VALUES('Engine Parts','engine-parts'),('Gearbox','gearbox'),('Suspension','suspension'),('Brakes','brakes'),('Electrical','electrical'),('Body Parts','body-parts');
INSERT INTO products(category_id,brand,name,slug,oem_number,description,price,stock,condition_grade) VALUES(1,'Toyota','Toyota 1NZ-FE Engine Unit','toyota-1nz-fe-engine','1NZ-FE','Quality checked reconditioned engine unit.',185000,3,'B'),(2,'Honda','Honda Fit CVT Gearbox','honda-fit-cvt-gearbox','CVT-FIT','Inspected reconditioned CVT gearbox.',165000,2,'B'),(3,'TEIN','TEIN Street Suspension Set','tein-street-suspension','TEIN-ST','Reconditioned suspension set.',145000,4,'A'),(4,'Brembo','Brembo Performance Brake Set','brembo-performance-brake','BRM-01','Performance brake set.',62500,6,'A'),(5,'Denso','Denso ECU Module','denso-ecu-module','DENSO-ECU','Tested electronic control module.',48000,5,'B');
-- Create an admin password hash yourself with PHP password_hash() before production.
-- Demo admin email: admin@jktech.lk
